#+OPTIONS:     H:2 num:nil toc:t \n:nil @:t ::t |:t ^:t f:t TeX:t ...

Encyclopedia Brown Solves Them All

Written by: Donald J. Sobol

Illustrated by: Leanord Shortall

* Overview
Encyclopedia Brown runs a business out of his garage that helps people solve problems.

* Characters:
** Encyclopedia Brown
Encyclopedia Brown helps his  police detective father solve cases over dinner table. His real name is Leroy Brown, but everyone calls him Encyclopedia, because he knows so much. He's checked out every book in the library.
** Bugs - Antagonist
** Various clients & villians

* Setting
Present day, in a small town, Idaville

* Plot
** Beginning
Kids come to Encyclopedia's garage and pay him 25c to have him help them with their problems. Encyclopedia asks them one or two questions,
and takes their cases.
** Middle
Encyclopedia searches for clues around town. He asks people for clues who are around the area where the mystery occurred.  
** End 
Each case ends with the solution. Was only able to solve one of the cases, they were really hard but it was fun to try.

* What did you think of the story?
Really liked it. Would definitely read more of them.